### ISSUE TITLE
Server not running when app is in background

### ISSUE THREAD

**Issue by rangav** [futurepress/react-native-static-server#29]
Hi 

Thanks for the great library.

When the app is in background the server is not running, i have started with below setting

`let server = new StaticServer(8080, path, { keepAlive: true });`

after going through the GCDWebServer documentation, we need to set GCDWebServerOption_ConnectedStateCoalescingInterval

`[options setObject:@2.0 forKey:GCDWebServerOption_ConnectedStateCoalescingInterval];
`

Ref https://github.com/swisspol/GCDWebServer/issues/333

can you please provide this option to set duration to keep running when app is in background

**Comment by kanalasumant** [comment]
@rangav great. I have another issue popping up and that is when the {localOnly: true} option not set, the server should potentially be able to serve files from also a browser instead of only from a webView from the app itself. Correct me if I'm wrong, but this doesn't seem to be the behaviour right now on any IOS/ Android device. Kindly let me know if this is the expected behaviour for you when you find the time. Thanks. Much appreciated. :)

**Comment by rangav** [comment]
Hi @kanalasumant 

When localOnly true is set it will start in localhost:port which will work on device, but to access it over local network from another device it should be with ipaddress:port.

I have tested with localOnly:false default value (i.e i did not set anything for this ) its working for me

The server will start from the directory specified, then you can access the files from browser.

Not sure this answered your question?

**Comment by kanalasumant** [comment]
I think, I understood what was going on. I left the localOnly option to be defaulted, thus the server would run in a browser, but since I'm leaving the app to see if the browser is serving, it fails to run and my guess is due to not setting keepAlive:true option as long as the lifetime of the app. Thanks. Hopefully this'll fix it.
