### ISSUE TITLE
46 Duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by JulianKingman** [futurepress/react-native-static-server#4]
Any idea why building in Xcode is giving me this issue? 
<img width="1121" alt="screen shot 2017-05-11 at 12 40 48 pm" src="https://cloud.githubusercontent.com/assets/1566400/25961128/2e559c88-3647-11e7-9cb4-f01771ca7601.png">

I'm using a detached Expo project, which uses Pods for some native dependencies, and then I'm including the React headers from the Pod folder in the Header Search Path. Here's what the header search paths look like:
<img width="925" alt="screen shot 2017-05-11 at 12 45 02 pm" src="https://cloud.githubusercontent.com/assets/1566400/25961260/adb1bde0-3647-11e7-9a4e-279c429df71a.png">

Thanks in advance!

**Comment by theebi** [comment]
<img width="728" alt="screen shot 2017-05-15 at 6 42 39 pm" src="https://cloud.githubusercontent.com/assets/19174530/26059151/51aa4ab2-399e-11e7-9c4c-8d0c3ffc4893.png">

I have the same issue. Do you have any fix for this?

**Comment by JulianKingman** [comment]
Nothing yet. Did you use ExpoKit, too? I tried creating a repo with `create-react-native-app` and I didn't get the linker error, so I assume it has something to do with the Pods.

**Comment by MustansirZia** [comment]
Hey there!
This issue occurs when you're using a detached Expo app. Now Expo uses Pods to fill in the native react dependencies for iOS. It doesn't follow the regular mode of adding its own libraries to your RN project. This repo uses CocoaLumberjack and so does Expo. So you have the same dependencies at two places. (CocoaLumberjack in your Target Libraries and CocoaLumberjack in your Pods). This is why it works without Expo.

To fix this, simply remove either. It's better that you remove the one that's used in this library since Expo might use its CocoaLumberjack somewhere else. 
To remove it follow these steps: 
• In the project window. Go to `YourApp` -> `Libraries` -> `FPStaticServer.xcodepoj`.
• Remove `CocoaLumberjack` folder by removing the reference. (As shown below)

<img width="1280" alt="screen shot 2017-08-12 at 4 35 16 pm" src="https://user-images.githubusercontent.com/14149485/29240345-f67f9ff6-7f80-11e7-89f2-c33ecb78d22c.png">
<img width="1280" alt="screen shot 2017-08-12 at 4 35 21 pm" src="https://user-images.githubusercontent.com/14149485/29240393-d2d5b256-7f81-11e7-899b-311f0d359734.png">

Hope it helps!

**Comment by fchasen** [comment]
Not sure the right solution for this -- CocoaLumberJack is optional for the server but would be useful to keep for logging.

**Comment by MustansirZia** [comment]
Well, that's why the error occurs. Since `CocoaLumberJack` is also part of the detached expo kit. This error could also be removed by allowing duplicate symbols during compilation (which would probably create redundancy though). Unfortunately, didn't get the chance to explore this further. Should be somewhere in build settings.

**Comment by vinXpro** [comment]
Any idea?? Same error

**Comment by MustansirZia** [comment]
@vinXpro Did you try the above solution?

**Comment by vinXpro** [comment]
@MustansirZia I try install again and give me this 

`> fsevents@1.1.2 install /Volumes/MacintoshHD2/Projects/RNWebServer/node_modules/fsevents
> node install

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-pre-gyp ENOENT
    at _errnoException (util.js:1041:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-native-static-server@0.2.2 requires a peer of react-native@^0.43.2 but none was installed.
npm WARN react-native@0.47.2 requires a peer of react@16.0.0-alpha.12 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ react-native-static-server@0.2.2
added 59 packages, removed 236 packages and updated 521 packages in 139.44s
Nguyens-MacBook-Pro:RNWebServer vinhnguyen$ code .
Nguyens-MacBook-Pro:RNWebServer vinhnguyen$ npm install react-native-static-server --save

> fsevents@1.1.2 install /Volumes/MacintoshHD2/Projects/RNWebServer/node_modules/fsevents
> node install

[fsevents] Success: "/Volumes/MacintoshHD2/Projects/RNWebServer/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN react-native-static-server@0.2.2 requires a peer of react-native@^0.43.2 but none was installed.
npm WARN react-native@0.47.2 requires a peer of react@16.0.0-alpha.12 but none was installed.

+ react-native-static-server@0.2.2
added 115 packages, removed 25 packages and updated 1 package in 70.922s`

**Comment by MustansirZia** [comment]
@vinXpro I don't quite understand what you're trying to do. Can you go back a little and describe what you did to solve the duplicate symbols issue?

**Comment by vinXpro** [comment]
@MustansirZia 
I try to create new project and I dont need try the above solution.
I dont know why but I tried this:
`watchman watch-del-all
rm -rf $TMPDIR/react-*
yarn cache clean && rm -rf node_modules/ && yarn install
`
and delete 'react-native' in /node_modules/react-native-static-server/package.json
`
"peerDependencies": {
    "react-native": "^0.43.2"
  },
  "dependencies": {
    "react-native": "^0.47.1"
}
`
and that works !!!

**Comment by MustansirZia** [comment]
@vinXpro Alright then! Sounds quite interesting. :)

**Comment by vinXpro** [comment]
@MustansirZia Thanks!! 
I have some questions: How to create sockets (emit, on...)? Its not supported?

**Comment by MustansirZia** [comment]
Sockets where? In react-native or this repository?

**Comment by vinXpro** [comment]
I want socket server to create to send data between clients and server. I think not supported this lib.

**Comment by fchasen** [comment]
Removed CocoaLumberJack
