### ISSUE TITLE
FPStaticServer is undefined

### ISSUE THREAD

**Issue by saggiyogesh** [futurepress/react-native-static-server#41]
While starting the server `FPStaticServer` is undefined, hence server is not started. 
Using RN@0.53.3

**Comment by alex-jgr** [comment]
I don't know if it exactly relates to this issue, but I had to downgrade react-native to version 0.52 in order to make this module work. In my case the Android Logcat was saying that the start() method is undefined. Please, if there's somebody still maintaining this package, try to adapt this module to higher versions of React Native. I downgraded when I noticed that there weren't any commits or releases in the past two months for this module, so I searched to see which version of RN was available two months ago. I need it to work with react-native@0.54 because it's the minimum version recommended for Viro to work with ARCore.

**Comment by saggiyogesh** [comment]
@alex-jgr 
Thanks for your pointers. Able to start the server on android with RN@ 0.52. 
But IOS is still giving issue while compling the app. 
Did you tried for ios also ?

**Comment by alex-jgr** [comment]
I don't know about the iOS part. Sorry

**Comment by JulianKingman** [comment]
@saggiyogesh in iOS, make sure it's linked in xcode. I'm using a detached version of Expo, and most libraries are linked through cocoapods, but this one requires manual linking.

<img width="866" alt="screen shot 2018-05-28 at 9 49 26 am" src="https://user-images.githubusercontent.com/1566400/40619974-b5c538c6-625c-11e8-9742-309255a311aa.png">

**Comment by saggiyogesh** [comment]
@JulianKingman Please let me know your environment details. I'll try in same.
`react-native info`, share the details given by this command.

**Comment by saggiyogesh** [comment]
@JulianKingman it worked on ios after upgrading mac os & xcode to latest and its working with latest RN also. Thanks.

**Comment by fchasen** [comment]
Great!
